### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Last-Modified"]

### ISSUE THREAD

**Issue by yoch** [vladmandic/build#1]
https://github.com/vladmandic/build/blob/c04284746e6ac7eaa84861e22029f5161b8a229b/src/serve.ts#L119

Adding `.toUTCString()` worked for me

**Comment by vladmandic** [comment]
strange as date object should be treated as number and auto-cast to string to start with  
but yes, explicit cast is a good practice - thanks for chasing this down!

new version is published
